name: $(BuildID)

trigger:
  batch: true
  branches:
    include:
    - master

variables:
- group: family-island-azure-variables

stages:
- stage: pack_and_upload_extension
  jobs:
  - job: pack_and_upload_extension
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self
      lfs: true
    - bash: |
        NAME=$(Build.Repository.Name)-$(Build.BuildNumber).zip
        zip -r ${NAME} . -x ".git*"
        az storage blob upload -f ${NAME} -n ${NAME} --container-name $AZURE_DEFOLD_EXTENSIONS_CONTAINER
        echo "URL is https://${AZURE_STORAGE_ACCOUNT}.blob.core.windows.net/${AZURE_DEFOLD_EXTENSIONS_CONTAINER}/${NAME}"
      env:
        AZURE_STORAGE_ACCOUNT: $(AZ_STORAGE_ACCOUNT)
        AZURE_STORAGE_KEY: $(AZ_STORAGE_KEY)
        AZURE_DEFOLD_EXTENSIONS_CONTAINER: $(AZ_DEFOLD_EXTENSIONS_CONTAINER)
      displayName: "pack_and_upload_extension"
