[websocket]
group = Runtime
help = Websocket extension settings
title = Websocket

buffer_size.type = integer
buffer_size.help = Size of the receive buffer
buffer_size.default = 65536

max_connections.type = integer
max_connections.help = Maximum number of concurrent connections
max_connections.default = 2

debug.type = string
debug.options = disabled:Disabled,state_changes:State changes,verbose:Verbose
debug.help = The debug level
debug.default = disabled

socket_timeout.type = integer
socket_timeout.default = 500000
socket_timeout.help = Timeout for the underlying socket connection, in microseconds
