[websocket]
group = Runtime
help = Websocket extension settings

buffer_size.type = integer
buffer_size.default = 65536

socket_timeout.type = integer
socket_timeout.default = 500000
socket_timeout.help = Timeout for the underlying socket connection, in microseconds

max_connections.type = integer
max_connections.default = 2


debug.type = integer
debug.default = 0
debug.options = 0:Disabled, 1:State Changes, 2:Messages Sent and Received
